### ISSUE TITLE
lỗi bilutvzz và biphim

### ISSUE THREAD

**Issue by Krazeecode** [billythekids/plugin.video.bimozie#31]
Biphim lỗi:
Trang biphim có 2 links, 1 là okru.biphim.club (VIP 2 trên web), còn link còn lại là link main biphim.club (VIP 1 trên web).
link okru nếu có setup trên trang chính thì xem được (VIP 2 link).
Nhưng link main (VIP 1) thì không xem được trên kodi mặc dù trên web vẫn xem link VIP 1 dc.

Bilutv lỗi:

2020-12-05 23:19:05.470 T:11433   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-12-05 23:20:27.538 T:12620   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ReadTimeout'>
                                            Error Contents: HTTPSConnectionPool(host='bilutvzz.net', port=443): Read timed out. (read timeout=30)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/default.py", line 13, in <module>
                                                app.router()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/resources/lib/app.py", line 739, in router
                                                movie = instance().getMovie(movie_item.get('id'))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/resources/lib/plugins/bilutv/plugin.py", line 30, in getMovie
                                                response = Request().get(url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/resources/lib/utils/mozie_request.py", line 40, in get
                                                allow_redirects=redirect, cookies=cookies, verify=verify, stream=stream)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 501, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 630, in send
                                                history = [resp for resp in gen] if allow_redirects else []
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 190, in resolve_redirects
                                                **adapter_kwargs
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 499, in send
                                                raise ReadTimeout(e, request=request)
                                            ReadTimeout: HTTPSConnectionPool(host='bilutvzz.net', port=443): Read timed out. (read timeout=30)
                                            -->End of Python script error report<--
2020-12-05 23:20:27.832 T:12619   ERROR: GetDirectory - Error getting plugin://plugin.video.bimozie/?className=Bilutv&mode=movie&module=bilutv.plugin&movie_item=%7b%22thumb%22%3a%20%22https%3a%2f%2fbilugo.com%2fupload%2fimages%2f2020%2f11%2fchi-vi-phut-giay-duoc-gap-em-2020_1606666223.jpg%22%2c%20%22title%22%3a%20%22Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%22%2c%20%22label%22%3a%20%22%5bT%5cu1eadp%2014%20%5d%20Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%20-%20Just%20to%20See%20You%20(2020)%22%2c%20%22realtitle%22%3a%20%22Just%20to%20See%20You%20(2020)%22%2c%20%22type%22%3a%20%22T%5cu1eadp%2014%20%22%2c%20%22id%22%3a%20%2217624%22%7d
2020-12-05 23:20:27.838 T:11433   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bimozie/?className=Bilutv&mode=movie&module=bilutv.plugin&movie_item=%7b%22thumb%22%3a%20%22https%3a%2f%2fbilugo.com%2fupload%2fimages%2f2020%2f11%2fchi-vi-phut-giay-duoc-gap-em-2020_1606666223.jpg%22%2c%20%22title%22%3a%20%22Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%22%2c%20%22label%22%3a%20%22%5bT%5cu1eadp%2014%20%5d%20Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%20-%20Just%20to%20See%20You%20(2020)%22%2c%20%22realtitle%22%3a%20%22Just%20to%20See%20You%20(2020)%22%2c%20%22type%22%3a%20%22T%5cu1eadp%2014%20%22%2c%20%22id%22%3a%20%2217624%22%7d) failed
2020-12-05 23:20:50.018 T:12654   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/default.py", line 13, in <module>
                                                app.router()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/resources/lib/app.py", line 739, in router
                                                movie = instance().getMovie(movie_item.get('id'))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/resources/lib/plugins/bilutv/plugin.py", line 31, in getMovie
                                                url = Movie().get_movie_link(response)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.bimozie/resources/lib/plugins/bilutv/parser/movie.py", line 13, in get_movie_link
                                                return soup.select_one("a.btn-see.btn-danger").get('href')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
2020-12-05 23:20:50.340 T:12653   ERROR: GetDirectory - Error getting plugin://plugin.video.bimozie/?className=Bilutv&mode=movie&module=bilutv.plugin&movie_item=%7b%22thumb%22%3a%20%22https%3a%2f%2fbilugo.com%2fupload%2fimages%2f2020%2f11%2fchi-vi-phut-giay-duoc-gap-em-2020_1606666223.jpg%22%2c%20%22title%22%3a%20%22Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%22%2c%20%22label%22%3a%20%22%5bT%5cu1eadp%2014%20%5d%20Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%20-%20Just%20to%20See%20You%20(2020)%22%2c%20%22realtitle%22%3a%20%22Just%20to%20See%20You%20(2020)%22%2c%20%22type%22%3a%20%22T%5cu1eadp%2014%20%22%2c%20%22id%22%3a%20%2217624%22%7d
2020-12-05 23:20:50.346 T:11433   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.bimozie/?className=Bilutv&mode=movie&module=bilutv.plugin&movie_item=%7b%22thumb%22%3a%20%22https%3a%2f%2fbilugo.com%2fupload%2fimages%2f2020%2f11%2fchi-vi-phut-giay-duoc-gap-em-2020_1606666223.jpg%22%2c%20%22title%22%3a%20%22Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%22%2c%20%22label%22%3a%20%22%5bT%5cu1eadp%2014%20%5d%20Ch%5cu1ec9%20V%5cu00ec%20Ph%5cu00fat%20Gi%5cu00e2y%20%5cu0110%5cu01b0%5cu1ee3c%20G%5cu1eb7p%20Em%20-%20Just%20to%20See%20You%20(2020)%22%2c%20%22realtitle%22%3a%20%22Just%20to%20See%20You%20(2020)%22%2c%20%22type%22%3a%20%22T%5cu1eadp%2014%20%22%2c%20%22id%22%3a%20%2217624%22%7d) failed

**Comment by billythekids** [comment]
Fixed
