### ISSUE TITLE
Animehay issue

### ISSUE THREAD

**Issue by tedomi2705** [billythekids/plugin.video.bimozie#8]
Hi Billy,

Bimozie is having problem issue with getting animehay link

Log file:
```
2019-12-01 18:45:50.355 T:110612   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\hongd\AppData\Roaming\Kodi\addons\plugin.video.bimozie\default.py", line 11, in <module>
                                                app.router()
                                              File "C:\Users\hongd\AppData\Roaming\Kodi\addons\plugin.video.bimozie\resources\lib\app.py", line 678, in router
                                                movie = instance().getLink(json.loads(url))
                                              File "C:\Users\hongd\AppData\Roaming\Kodi\addons\plugin.video.bimozie\resources\lib\plugins\animehay\plugin.py", line 32, in getLink
                                                return Movie().get_link(response)
                                              File "C:\Users\hongd\AppData\Roaming\Kodi\addons\plugin.video.bimozie\resources\lib\plugins\animehay\parser\movie.py", line 50, in get_link
                                                vkey = re.search('key=(.*)', sources.group(1)).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
```
[kodi.log](https://github.com/billythekids/plugin.video.bimozie/files/3908159/kodi.log)

**Comment by billythekids** [comment]
Hi hongducthbk123
Seems their server is down. i couldn't access to website got cloudflare  error message

**Comment by billythekids** [comment]
Animehay fixed
